### ISSUE TITLE
Any issues?

### ISSUE THREAD

**Issue by volodymyr-kushnir** [AndrewMateshchuk/BinaryAcademyProject#1]
Hey, @AndrewMateshchuk, how's it going?

Бачу жодних проблем в Issues, то напевно підкажу декілька — файли можна в *.md, форматування в *.md, до репозиторію додати README.md з описом і лінками на файли.
Бачу проект є, це плюс в карму, але в проекті тільки одна колонка, якби були ще "Backlog", "Ready", "In progress" шоб менеджер бачив процес розробки — було б два плюси в карму.
По всем вопросам обращайтесь — just give me a shout with @volodymyr-kushnir if you've got any questions.

**Comment by AndrewMateshchuk** [comment]
Додав колонки у проект, та файл README!
